[package]
name = "torrosion"
version = "0.5.1"
edition = "2021"
repository = "https://github.com/AS207960/libtor"
authors = ["Q Misell <q@as207960.net>"]
description = "A Tor library for Rust"
readme = "../README.md"
homepage = "https://acmeforonions.org"
license = "MIT"
exclude = ["/update_fallback.sh"]

[dependencies]
hex = "0.4"
log = "0.4"
rand = "0.10.0-rc.6"
regex = "1"
semver = "1"
lazy_static = "1"
chrono = "0.4"
byteorder = "1"
ring = "0.17"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "fs"] }
tokio-util = { version = "0.7", features = ["io"] }
tokio-rustls = "0.26"
tokio-stream = { version = "0.1", features = ["io-util"] }
x509-parser = "0.18"
oid-registry = "0.8"
rsa = "0.10.0-rc.12"
aes = "0.9.0-rc.2"
ctr = "0.10.0-rc.2"
hyper = { version = "1", features = ["client", "http1"] }
hyper-util = { version = "0.1", features = ["client", "client-legacy", "http1"] }
futures = "0.3"
async-compression = { version = "0.4", features = ["tokio", "zlib", "zstd", "xz"] }
async-native-tls = { version = "0.5", features = ["runtime-tokio"], default-features = false }
base64 = "0.22"
base32 = "0.5"
sha3 = "0.10"
curve25519-dalek = "5.0.0-pre.4"
ed25519-dalek = "3.0.0-pre.4"
x25519-dalek = { version = "3.0.0-pre.4", features = ["static_secrets"] }
hkdf = "0.12"
sha2 = "0.10"
http = "1"
digest = "0.10.6"
sha1 = "0.10.5"
tower = "0.5.0"
http-body-util = "0.1.2"
bytes = "1.7.1"
constant_time_eq = "0.4.2"
dynosaur = "0.3.0"
